<?php

namespace Clearlyip\LaravelFlipt\Enums;

enum ConstraintComparisonType: string
{
    case UNKNOWN_CONSTRAINT_COMPARISON_TYPE = 'UNKNOWN_CONSTRAINT_COMPARISON_TYPE';
    case STRING_CONSTRAINT_COMPARISON_TYPE = 'STRING_CONSTRAINT_COMPARISON_TYPE';
    case NUMBER_CONSTRAINT_COMPARISON_TYPE = 'NUMBER_CONSTRAINT_COMPARISON_TYPE';
    case BOOLEAN_CONSTRAINT_COMPARISON_TYPE = 'BOOLEAN_CONSTRAINT_COMPARISON_TYPE';
    case DATETIME_CONSTRAINT_COMPARISON_TYPE = 'DATETIME_CONSTRAINT_COMPARISON_TYPE';
    case ENTITY_ID_CONSTRAINT_COMPARISON_TYPE = 'ENTITY_ID_CONSTRAINT_COMPARISON_TYPE';
}
