<?php

namespace Clearlyip\LaravelFlipt\Enums;

enum Reason: string
{
    case UNKNOWN_EVALUATION_REASON = 'UNKNOWN_EVALUATION_REASON';
    case FLAG_DISABLED_EVALUATION_REASON = 'FLAG_DISABLED_EVALUATION_REASON';
    case MATCH_EVALUATION_REASON = 'MATCH_EVALUATION_REASON';
    case DEFAULT_EVALUATION_REASON = 'DEFAULT_EVALUATION_REASON';
}
